### ISSUE TITLE
[Submit a Vocabulary]: test

### ISSUE THREAD

**Issue by j9magayanes** [os-deib/deib-inclusion-checker#11]
### What Vocabularyn do you want us to add?

I want to submit this set of new vocabulary : english

### File Upload

[List of Words (to check).csv](https://github.com/os-deib/deib-inclusion-checker/files/14627149/List.of.Words.to.check.csv)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CoachBirgit** [comment]
cleanup test issues for workflow building
