### ISSUE TITLE
[Bug]: sample

### ISSUE THREAD

**Issue by j9magayanes** [os-deib/deib-inclusion-checker#13]
### What happened?

A bug happened!

### Version

1.0 (Default)

### What browsers are you seeing the problem on?

Chrome

### File Upload

[text.txt](https://github.com/os-deib/deib-inclusion-checker/files/14627180/text.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CoachBirgit** [comment]
cleanup test issues for workflow building
